import Head from 'next/head'

// Components
import Footer from '../components/footer.component'
import Greet from '../components/home/greet.component'

// Sections
import Consortium from '../sections/home/consortium.section'
import CurrentChallenges from '../sections/home/currentChallenges.section'
import JoinUs from '../sections/home/joinUs.section'
import MainGoal from '../sections/home/mainGoal.section'
import WhoAreWe from '../sections/home/whoAreWe.section'
import Partners from '../sections/home/partners.section'
import Ecosystem from '../sections/home/ecosystem.section'
import Membership from '../sections/home/membership.section'
import Button from '../components/button.component'
import Gamified from '../sections/home/gamified.section'

export default function Home() {
  return (
    <div className='overflow-x-hidden'>
      <Head>
        <title>Centauri</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Greet />
      <div className='flex flex-col justify-center items-center gap-20 text-white mx-auto my-16 px-10'>
        {/* Apply for membership section*/}
        <div className='mb-40 text-center'>
          <p className='text-5xl font-extralight my-14'>Apply for membership <span className='font-bold'>here</span></p>
          <Button label='Click here to apply' handleClick={() => window.open('https://docs.google.com/forms/d/e/1FAIpQLSdI7VaZN5Yc-6C7dhCw1oELcfU6K60Wg6X1HFD8MkjN97KqNA/viewform', '_blank')} />
        </div>

        {/* Who are we section*/}
        <WhoAreWe />
        {/* The main goal section*/}
        <MainGoal />

        {/* Blue hole section */}
        <div className='flex flex-col relative w-full gap-60 justify-center'>
          {/* blue hole */}
          <div className='absolute w-[973px] h-[1206px] bg-[#627BFF] rounded-full -right-[900px] blur-[100px]' />
          {/* The centauri consortium section */}
          <Consortium />
          {/* Current challenges section */}
          <CurrentChallenges />
        </div>

        {/*  */}

        {/* OUR WEB3 USP: A GAMIFIED DAO section */}
        <Gamified />

        {/* Three holes section */}
        <div className='relative flex flex-col gap-40 my-40 justify-center items-center'>
          {/* Holes */}
          <div className='absolute bg-[#C840A9] rounded-full w-[900px] h-[900px] blur-[100px] top-[200px]' />
          <div className='absolute bg-[#627BFF] rounded-full w-[743px] h-[743px] blur-[100px] -left-[400px]' />
          <div className='absolute bg-[#F3DE6B] rounded-full w-[400px] h-[400px] blur-[200px] -right-[200px] top-0' />

          {/* Ecosystem */}
          <Ecosystem />
          {/* Founding Partners */}
          <Partners />
        </div>

        {/* Membership section */}
        <Membership />
        {/* Join Us section */}
        <JoinUs />
      </div >
      <Footer />
    </div>
  )
}
