import Head from 'next/head'
import Footer from '../components/footer.component'
import Greet from '../components/home/greet.component'

export default function Home() {
  return (
    <>
      <Head>
        <title>Centauri</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Greet />
      <div className='flex flex-col justify-center items-center gap-20 max-w-[100rem] text-white mx-auto my-16'>
        {/* Apply for membership */}
        <div>

        </div>

        {/* Who are we */}
        <div className='w-full grid grid-cols-2 justify-center items-center gap-28'>
          <div className='relative flex justify-center items-center'>
            <div className='absolute w-[421px] h-[421px] rounded-full bg-[#F3DE6B] blur-[100px]' />
            <div className='absolute w-[421px] h-[421px] rounded-full bg-black' />
            <p className='absolute text-[7.25rem] leading-none font-bold w-64 right-20'>WHO ARE WE?</p>
          </div>
          <p className='text-2xl max-w-3xl font-extralight leading-relaxed'>The Centauri Web3 Consortium is dedicated to fostering the development and adoption of web3 through the creation of open and transparent standards. Our goal is to build a harmonized and scalable ecosystem with interoperability at its core. We strive to educate, standardize, and enable web3 adoption for businesses and creators alike by developing "The Metanode" hive, a platform that brings together the best of web3 technology and makes it accessible and user-friendly for all. We invite you to join us in shaping the future of the web.</p>
        </div>

        {/* The main goal */}
        <div className='w-full grid grid-cols-2 justify-center items-center gap-28'>
          <p className='text-[7.25rem] font-extralight'>The main goal</p>
          <div>
            <p className='text-2xl max-w-3xl font-extralight leading-relaxed'>The main goal of the Centauri Web3 Consortium is to foster the development and adoption of web3 through the creation of open and transparent standards to build a harmonized and scalable ecosystem with interoperability at its core.</p>
            <p className='text-2xl max-w-3xl font-extralight leading-relaxed'>The Centauri Web3 Consortium is educating, standardizing and enabling web3 adoption for businesses and creators by building “The Metanode” hive.</p>
          </div>
        </div>

      </div >



      <Footer />
    </>
  )
}
